apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plugin-server.fullname" . }}
  labels: {{ include "plugin-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pluginServer.deployment.replicas }}
  selector:
    matchLabels: {{ include "plugin-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels: {{ include "plugin-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector: {{ include "linux-node-selector" . | nindent 8 }}
{{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      tolerations: {{ include "linux-node-tolerations" . | nindent 8 }}
{{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: {{ include "plugin-server.fullname" . }}
          securityContext: {{ toYaml .Values.pluginServer.securityContext | nindent 12 }}
          image: "{{ .Values.pluginServer.image.repository }}:{{ .Values.pluginServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pluginServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
            readOnly: true
            name: {{ include "plugin-server.fullname" . }}-nginx-conf
          resources:
      {{- with .Values.pluginServer.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "plugin-server.fullname" . }}-nginx-conf
          configMap:
            name: {{ include "plugin-server.fullname" . }}-nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: nginx.conf
                path: nginx.conf
