apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plugin-server.fullname" . }}-nginx-conf
  labels: {{ include "plugin-server.labels" . | nindent 4 }}
data:
{{ tpl (.Files.Glob "files/*").AsConfig . | indent 2 }}
