{{- $namespaces := dict "_0" .Release.Namespace -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "plugin-server.fullname" . }}
  labels: {{ include "plugin-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "plugin-server.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "plugin-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "plugin-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "plugin-server.labels" . | nindent 4 }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "plugin-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "plugin-server.labels" . | nindent 4 }}
spec:
  privileged: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
  volumes:
    - 'secret'
